// INGLESE
easy = [
  'Abuse',
  'Adult',
  'Agent',
  'Anger',
  'Apple',
  'Award',
  'Basis',
  'Beach',
  'Birth',
  'Block',
  'Blood',
  'Board',
  'Brain',
  'Bread',
  'Break',
  'Brown',
  'Buyer',
  'Cause',
  'Chain',
  'Chair',
  'Chest',
  'capocchia',
  'Chief',
  'Child',
  'China',
  'Claim',
  'Class',
  'Clock',
  'Coach',
  'Coast',
  'Court',
  'Cover',
  'Cream',
  'Crime',
  'Cross',
  'Crowd',
  'Crown',
  'Cycle',
  'Dance',
  'Death',
  'Depth',
  'Doubt',
  'Draft',
  'Drama',
  'Dream',
  'Dress',
  'Drink',
  'Drive',
  'Earth',
  'Enemy',
  'Entry',
  'Error',
  'Event',
  'Faith',
  'Fault',
  'Field',
  'Fight',
  'Final',
  'Floor',
  'Focus',
  'Force',
  'Frame',
  'Frank',
  'Front',
  'Fruit',
  'Glass',
  'Grant',
  'Grass',
  'Green',
  'Group',
  'Guide',
  'Heart',
  'Henry',
  'Horse',
  'Hotel',
  'House',
  'Image',
  'Index',
  'Input',
  'Issue',
  'Japan',
  'Jones',
  'Judge',
  'Knife',
  'Laura',
  'Layer',
  'Level',
  'Lewis',
  'Light',
  'Limit',
  'Lunch',
  'Major',
  'March',
  'Match',
  'Metal',
  'Model',
  'Money',
  'Month',
  'Motor',
  'Mouth',
  'Music',
  'Night',
  'Noise',
  'North',
  'Novel',
  'Nurse',
  'Offer',
  'Order',
  'Other',
  'Owner',
  'Panel',
  'Paper',
  'Party',
  'Peace',
  'Peter',
  'Phase',
  'Phone',
  'Piece',
  'Pilot',
  'Pitch',
  'Place',
  'Plane',
  'Plant',
  'Plate',
  'Point',
  'Pound',
  'Power',
  'Press',
  'Price',
  'Pride',
  'Prize',
  'Proof',
  'Queen',
  'Radio',
  'Range',
  'Ratio',
  'Reply',
  'Right',
  'River',
  'Round',
  'Route',
  'Rugby',
  'Scale',
  'Scene',
  'Scope',
  'Score',
  'Sense',
  'Shape',
  'Share',
  'Sheep',
  'Sheet',
  'Shift',
  'Shirt',
  'Shock',
  'Sight',
  'Simon',
  'Skill',
  'Sleep',
  'Smile',
  'Smith',
  'Smoke',
  'Sound',
  'South',
  'Space',
  'Speed',
  'Spite',
  'Sport',
  'Squad',
  'Staff',
  'Stage',
  'Start',
  'State',
  'Steam',
  'Steel',
  'Stock',
  'Stone',
  'Store',
  'Study',
  'Stuff',
  'Style',
  'Sugar',
  'Table',
  'Taste',
  'Terry',
  'Theme',
  'Thing',
  'Title',
  'Total',
  'Touch',
  'Tower',
  'Track',
  'Trade',
  'Train',
  'Trend',
  'Trial',
  'Trust',
  'Truth',
  'Uncle',
  'Union',
  'Unity',
  'Value',
  'Video',
  'Visit',
  'Voice',
  'Waste',
  'Watch',
  'Water',
  'While',
  'White',
  'Whole',
  'Woman',
  'World',
  'Youth',
];
medium = [
  'absolute',
  'abstract',
  'academic',
  'accepted',
  'accident',
  'accuracy',
  'accurate',
  'achieved',
  'acquired',
  'activity',
  'actually',
  'addition',
  'adequate',
  'adjacent',
  'adjusted',
  'advanced',
  'advisory',
  'aluminum',
  'analysis',
  'horcrux',
  'announce',
  'anything',
  'anywhere',
  'apparent',
  'appendix',
  'approach',
  'approval',
  'argument',
  'artistic',
  'assembly',
  'assuming',
  'athletic',
  'attached',
  'attitude',
  'attorney',
  'audience',
  'autonomy',
  'aviatio',
  'ceremony',
  'chairman',
  'champion',
  'chemical',
  'children',
  'circular',
  'civilian',
  'clearing',
  'clinical',
  'clothing',
  'collapse',
  'colonial',
  'colorful',
  'commence',
  'commerce',
  'complain',
  'complete',
  'composed',
  'compound',
  'comprise',
  'computer',
  'conclude',
  'concrete',
  'conflict',
  'confused',
  'congress',
  'consider',
  'contrast',
  'convince',
  'corridor',
  'coverage',
  'covering',
  'creation',
  'creative',
  'criminal',
  'critical',
  'crossing',
  'cultural',
  'currency',
  'customer',
  'database',
  'daughter',
  'daylight',
  'deadline',
  'deciding',
  'decision',
  'decrease',
  'deferred',
  'definite',
  'delicate',
  'delivery',
  'describe',
  'designer',
  'detailed',
  'diabetes',
  'dialogue',
  'diameter',
  'directly',
  'director',
  'discover',
  'disorder',
  'disposal',
  'distance',
  'distinct',
  'district',
  'dividend',
  'division',
  'doctrine',
  'document',
  'domestic',
  'dominant',
  'dominate',
  'doubtful',
  'dramatic',
  'dressing',
  'dropping',
  'election',
  'electric',
  'eligible',
  'emerging',
  'emphasis',
  'employee',
  'endeavor',
  'engaging',
  'engineer',
  'enormous',
  'entirely',
  'entrance',
  'envelope',
  'equality',
  'equation',
  'estimate',
  'evaluate',
  'eventual',
  'everyday',
  'everyone',
  'evidence',
  'exchange',
  'exciting',
  'exercise',
  'explicit',
  'exposure',
  'festival',
  'finished',
  'firewall',
  'flagship',
  'flexible',
  'floating',
  'football',
  'foothill',
  'forecast',
  'foremost',
  'formerly',
  'fourteen',
  'fraction',
  'franklin',
  'frequent',
  'friendly',
  'frontier',
  'generate',
  'generous',
  'genomics',
  'goodwill',
  'governor',
  'graduate',
  'graphics',
  'grateful',
  'guardian',
  'guidance',
  'handling',
  'hardware',
  'heritage',
  'highland',
  'historic',
  'homeless',
  'homepage',
  'hospital',
  'humanity',
  'identify',
  'identity',
  'ideology',
  'imperial',
  'incident',
  'included',
  'increase',
  'indicate',
  'indirect',
  'industry',
  'informal',
  'informed',
  'integral',
  'intended',
  'interact',
  'interest',
  'interior',
  'internal',
  'interval',
  'intimate',
  'intranet',
  'invasion',
  'involved',
  'isolated',
  'judgment',
  'judicial',
  'junction',
  'keyboard',
  'landlord',
  'language',
  'laughter',
  'learning',
  'leverage',
  'lifetime',
  'lighting',
  'likewise',
  'limiting',
  'literary',
  'location',
  'magazine',
  'magnetic',
  'maintain',
  'majority',
  'marginal',
  'marriage',
  'material',
  'memorial',
  'merchant',
  'midnight',
  'military',
  'minimize',
  'minister',
  'ministry',
  'minority',
  'mobility',
  'modeling',
  'moderate',
  'momentum',
  'monetary',
  'moreover',
  'mortgage',
  'mountain',
  'mounting',
  'movement',
  'multiple',
  'national',
  'negative',
  'nineteen',
  'northern',
  'notebook',
  'numerous',
  'observer',
  'occasion',
  'offering',
  'official',
  'offshore',
  'operator',
  'opponent',
  'opposite',
  'optimism',
  'optional',
  'ordinary',
  'organize',
  'original',
  'overcome',
  'overhead',
  'overseas',
  'overview',
  'painting',
  'parallel',
  'parental',
  'patented',
  'patience',
  'peaceful',
  'periodic',
  'personal',
  'persuade',
  'petition',
  'physical',
  'pipeline',
  'platform',
  'pleasant',
  'pleasure',
  'politics',
  'portable',
  'portrait',
  'position',
  'positive',
  'possible',
  'powerful',
  'practice',
  'precious',
  'pregnant',
  'presence',
  'preserve',
  'pressing',
  'pressure',
  'previous',
  'princess',
  'printing',
  'priority',
  'probable',
  'probably',
  'provided',
  'provider',
  'province',
  'publicly',
  'purchase',
  'pursuant',
  'quantity',
  'question',
  'rational',
  'reaction',
  'required',
  'research',
  'reserved',
  'resident',
  'resigned',
  'scrutiny',
  'seasonal',
  'secondly',
  'security',
  'sensible',
  'sentence',
  'separate',
  'sequence',
  'sergeant',
  'shipping',
  'shortage',
  'shoulder',
  'simplify',
  'situated',
  'slightly',
  'software',
  'solution',
  'somebody',
  'somewhat',
  'southern',
  'speaking',
  'specific',
  'spectrum',
  'sporting',
  'standard',
  'standing',
  'standout',
  'suburban',
  'suitable',
  'superior',
  'supposed',
  'surgical',
  'surprise',
  'survival',
  'sweeping',
  'swimming',
  'symbolic',
  'sympathy',
  'syndrome',
  'tactical',
  'tailored',
  'takeover',
  'tangible',
  'taxation',
  'taxpayer',
  'teaching',
  'tendency',
  'terminal',
  'terrible',
  'tracking',
  'training',
  'transfer',
  'traveled',
  'treasury',
  'triangle',
  'tropical',
  'turnover',
  'ultimate',
  'umbrella',
  'universe',
  'unlawful',
  'unlikely',
  'valuable',
  'variable',
  'vertical',
  'victoria',
  'violence',
  'volatile',
  'warranty',
  'weakness',
  'weighted',
  'whatever',
  'whenever',
  'wherever',
  'wildlife',
  'wireless',
  'withdraw',
  'woodland',
  'workshop',
  'yourself',
  'Ability',
  'Absence',
  'Academy',
  'Account',
  'Accused',
  'Achieve',
  'Acquire',
  'Address',
  'Advance',
  'Adverse',
  'Advised',
  'Adviser',
  'Against',
  'Airline',
  'Airport',
  'Alcohol',
  'Alleged',
  'Already',
  'Analyst',
  'Ancient',
  'Another',
  'Assault',
  'Assumed',
  'Assured',
  'Attempt',
  'Attract',
  'Auction',
  'Average',
  'Backing',
  'Balance',
  'Banking',
  'Barrier',
  'Battery',
  'Bearing',
  'Beating',
  'Brother',
  'Brought',
  'Burning',
  'Cabinet',
  'Caliber',
  'Calling',
  'Capable',
  'Capital',
  'Captain',
  'Caption',
  'Capture',
  'Careful',
  'Carrier',
  'Caution',
  'Ceiling',
  'Central',
  'Centric',
  'Century',
  'Certain',
  'Chamber',
  'Channel',
  'Chapter',
  'Charity',
  'Charlie',
  'Charter',
  'Checked',
  'Chicken',
  'Chronic',
  'Circuit',
  'Classes',
  'Classic',
  'Climate',
  'Closing',
  'Closure',
  'Clothes',
  'Collect',
  'Compete',
  'Complex',
  'Concept',
  'Concern',
  'Concert',
  'Conduct',
  'Confirm',
  'Connect',
  'Consent',
  'Consist',
  'Contact',
  'Contain',
  'Content',
  'Contest',
  'Context',
  'Control',
  'Convert',
  'Correct',
  'Council',
  'Counsel',
  'Counter',
  'Country',
  'Crucial',
  'Crystal',
  'Culture',
  'Current',
  'Cutting',
  'Dealing',
  'Decided',
  'Decline',
  'Default',
  'Defence',
  'Deficit',
  'Deliver',
  'Density',
  'Deposit',
  'Desktop',
  'Despite',
  'Destroy',
  'Develop',
  'Devoted',
  'Diamond',
  'Digital',
  'Discuss',
  'Disease',
  'Display',
  'Dispute',
  'Distant',
  'Diverse',
  'Divided',
  'Drawing',
  'Driving',
  'Dynamic',
  'Eastern',
  'Economy',
  'Edition',
  'Elderly',
  'Element',
  'Engaged',
  'Enhance',
  'Essence',
  'Evening',
  'Evident',
  'Exactly',
  'Examine',
  'Example',
  'Excited',
  'Exclude',
  'Exhibit',
  'Expense',
  'Explain',
  'Explore',
  'Express',
  'Extreme',
  'Factory',
  'Fifteen',
  'Filling',
  'Finance',
  'Finding',
  'Fishing',
  'Fitness',
  'Foreign',
  'Forever',
  'picciacca',
  'Formula',
  'Fortune',
  'Forward',
  'Founder',
  'Freedom',
  'Further',
  'Gallery',
  'Gateway',
  'General',
  'Genetic',
  'Genuine',
  'Hearing',
  'Heavily',
  'Helpful',
  'Helping',
  'Herself',
  'Highway',
  'Himself',
  'History',
  'Holding',
  'Holiday',
  'Housing',
  'However',
  'Hundred',
  'Husband',
  'Illegal',
  'Illness',
  'Imagine',
  'Imaging',
  'Improve',
  'Include',
  'Initial',
  'Inquiry',
  'Insight',
  'Install',
  'Instant',
  'Instead',
  'Intense',
  'Interim',
  'Involve',
  'Jointly',
  'Journal',
  'Journey',
  'Justice',
  'Justify',
  'Keeping',
  'Killing',
  'Kingdom',
  'Kitchen',
  'Knowing',
  'Landing',
  'Largely',
  'Lasting',
  'Leading',
  'Learned',
  'Leisure',
  'Liberal',
  'Liberty',
  'Library',
  'Manager',
  'Married',
  'Massive',
  'Maximum',
  'Meaning',
  'Measure',
  'Medical',
  'Meeting',
  'Mention',
  'Message',
  'Million',
  'Mineral',
  'Minimal',
  'Minimum',
  'Missing',
  'Mission',
  'Mistake',
  'Nervous',
  'Network',
  'Neutral',
  'Notable',
  'Nothing',
  'Nowhere',
  'Nuclear',
  'Nursing',
  'Obvious',
  'Offense',
  'Officer',
  'Ongoing',
  'Opening',
  'Operate',
  'Opinion',
  'Optical',
  'Organic',
  'Outcome',
  'Outdoor',
  'Parking',
  'Partial',
  'Partner',
  'Passage',
  'Passing',
  'Passion',
  'Passive',
  'Patient',
  'Pattern',
  'Payable',
  'Payment',
  'Penalty',
  'Pending',
  'Pension',
  'Percent',
  'Perfect',
  'Perform',
  'Perhaps',
  'Phoenix',
  'Picking',
  'Picture',
  'Pioneer',
  'Plastic',
  'Pointed',
  'Popular',
  'Portion',
  'Poverty',
  'Precise',
  'Predict',
  'Premier',
  'Premium',
  'Prepare',
  'Present',
  'Prevent',
  'Primary',
  'Printer',
  'Privacy',
  'Private',
  'Problem',
  'Proceed',
  'Process',
  'Produce',
  'Product',
  'Protein',
  'Protest',
  'Provide',
  'Publish',
  'Purpose',
  'Pushing',
  'Qualify',
  'Quality',
  'Quarter',
  'Radical',
  'Railway',
  'Readily',
  'Reading',
  'Reality',
  'Realize',
  'Receipt',
  'Removed',
  'Replace',
  'Request',
  'Require',
  'Reserve',
  'Resolve',
  'Respect',
  'Respond',
  'Restore',
  'Retired',
  'Revenue',
  'Reverse',
  'Rollout',
  'Routine',
  'Running',
  'Satisfy',
  'Science',
  'Section',
  'Segment',
  'Serious',
  'Service',
  'Serving',
  'Session',
  'Setting',
  'Seventh',
  'Several',
  'Shortly',
  'Showing',
  'Silence',
  'Silicon',
  'Similar',
  'Sitting',
  'Sixteen',
  'Skilled',
  'Smoking',
  'Society',
  'Somehow',
  'Someone',
  'Speaker',
  'Special',
  'Species',
  'Sponsor',
  'Station',
  'Storage',
  'Strange',
  'Stretch',
  'Student',
  'Studied',
  'Subject',
  'Succeed',
  'Success',
  'Suggest',
  'Summary',
  'Support',
  'Suppose',
  'Supreme',
  'Tension',
  'Theatre',
  'Therapy',
  'Thereby',
  'Thought',
  'Through',
  'Tonight',
  'Totally',
  'Touched',
  'Towards',
  'Traffic',
  'Trouble',
  'Turning',
  'Typical',
  'Uniform',
  'Unknown',
  'Unusual',
  'Upgrade',
  'Upscale',
  'Utility',
  'Variety',
  'Various',
  'Vehicle',
  'Venture',
  'Version',
  'Veteran',
  'Victory',
  'Viewing',
  'Village',
  'Violent',
  'Virtual',
  'Visible',
  'Waiting',
  'Walking',
  'Wanting',
  'Warning',
  'Warrant',
  'Wearing',
  'Weather',
  'Webcast',
  'Website',
  'Wedding',
  'Whether',
  'Willing',
  'Winning',
  'Without',
  'Witness',
  'Working',
  'Writing',
  'Written',
];
hard = [
  'Alchemized',
  'Amberjacks',
  'Apoenzymes',
  'Applejacks',
  'Appreciate',
  'Aquaphobes',
  'Aquaphobia',
  'Aquaphobic',
  'Asexualize',
  'Autoxidize',
  'Axiomatize',
  'Azobenzene',
  'Backchecks',
  'Backpacked',
  'Backpacker',
  'Balkanized',
  'Bamboozled',
  'Bedazzling',
  'Bedjackets',
  'Bhikkhunis',
  'Blackbucks',
  'Blackcocks',
  'Blackjacks',
  'Blitzkrieg',
  'Blizzarded',
  'Blizzardly',
  'Bodychecks',
  'Bolshevize',
  'Buckjumped',
  'Buckjumper',
  'Bumfreezer',
  'Catechizes',
  'Chabazites',
  'Chaptalize',
  'Checkboxes',
  'Checkmarks',
  'Chequebook',
  'Chernozems',
  'Chickenpox',
  'Chiffchaff',
  'Chimpanzee',
  'Chinquapin',
  'Chromizing',
  'Chymifying',
  'Cinchonize',
  'Circumflex',
  'Cognizably',
  'Colloquize',
  'Communized',
  'Complexify',
  'Complexity',
  'Crackajack',
  'Crazyweeds',
  'Cyclohexyl',
  'Dazzlement',
  'Dazzlingly',
  'Deoxidized',
  'Deoxidizer',
  'Deoxidizes',
  'Diazotized',
  'Diazotizes',
  'Dizzyingly',
  'Doxography',
  'Effeminize',
  'Embezzlers',
  'Embezzling',
  'Empathized',
  'Emphasized',
  'Enzymology',
  'Epoxidized',
  'Epoxidizes',
  'Equalizers',
  'Equalizing',
  'Equivoques',
  'Euphemized',
  'Everything',
  'Exahertzes',
  'Exchequers',
  'Exorcizing',
  'Exoticized',
  'Exoticizes',
  'Expertized',
  'Fetichized',
  'Fetichizes',
  'Friendship',
  'Frizzliest',
  'Gadzookery',
  'Grizzliest',
  'Hokeypokey',
  'Holoenzyme',
  'Homozygote',
  'Homozygous',
  'Hybridized',
  'Hybridizer',
  'Hybridizes',
  'Hydrazides',
  'Hydroxylic',
  'Hyphenized',
  'Hyphenizes',
  'Hypnotized',
  'Hypnotizer',
  'Hypnotizes',
  'Hypoxaemia',
  'Hypoxemias',
  'Intermezzi',
  'Intermezzo',
  'Jabberwock',
  'Jackhammer',
  'Jacklights',
  'Jackrabbit',
  'Jargonized',
  'Jargonizes',
  'Jayhawkers',
  'Jaywalkers',
  'Jaywalking',
  'Jeopardize',
  'Jockeyship',
  'Johnnycake',
  'Joypopping',
  'Jumboizing',
  'Juvenilize',
  'Juxtaposed',
  'Karyolymph',
  'Kazatskies',
  'Kibbitzing',
  'Kibbutznik',
  'Kickboxers',
  'Kickboxing',
  'Knickknack',
  'Knockbacks',
  'Kolkhoznik',
  'Lexicalize',
  'Liquidized',
  'Liquidizer',
  'Liquidizes',
  'Mezzanines',
  'Mezzotints',
  'Microquake',
  'Mizzenmast',
  'Morbidezza',
  'Motivation',
  'Mozzarella',
  'Mycorrhiza',
  'Mythicized',
  'Mythicizer',
  'Mythicizes',
  'Myxoedemic',
  'Myxomycete',
  'Nephropexy',
  'Outdazzled',
  'Outdazzles',
  'Oxidizable',
  'Oxycephaly',
  'Oxygenized',
  'Oxygenizer',
  'Oxygenizes',
  'Packetized',
  'Packetizes',
  'Paddywhack',
  'Passamezzo',
  'Paycheques',
  'Photolyzed',
  'Photolyzes',
  'Phyllotaxy',
  'Phytophagy',
  'Phytotoxic',
  'Pipsqueaks',
  'Pozzolanic',
  'Prequalify',
  'Puzzledoms',
  'Puzzlement',
  'Puzzlingly',
  'Pyrolyzing',
  'Quadplexes',
  'Quadraplex',
  'Quadratrix',
  'Quadruplex',
  'Quantizers',
  'Quantizing',
  'Quartzites',
  'Quatorzain',
  'Quickbeams',
  'Quicklimes',
  'Quicksteps',
  'Quillbacks',
  'Quinaquina',
  'Quincunxes',
  'Quixotical',
  'Quizmaster',
  'Razorbacks',
  'Rejuvenize',
  'Schizziest',
  'Schmoozing',
  'Schnozzles',
  'Schvitzing',
  'Scuzzballs',
  'Sexualized',
  'Shemozzled',
  'Shemozzles',
  'Showjumper',
  'Sjambokked',
  'Skyjackers',
  'Skyjacking',
  'Snazziness',
  'Squeezable',
  'Squeezebox',
  'Squeeziest',
  'Squirarchy',
  'Strawberry',
  'Subjectify',
  'Supplejack',
  'Symbolized',
  'Symptomize',
  'Synonymize',
  'Syphilized',
  'Syphilizes',
  'Tetrazzini',
  'Texturized',
  'Trihydroxy',
  'Undazzling',
  'Unmuzzling',
  'Unoxidized',
  'Unpuzzling',
  'Vampirized',
  'Victimized',
  'Viziership',
  'Vizirships',
  'Whizzbangs',
  'Whizzingly',
  'Xanthophyl',
  'Xerophytic',
  'Xiphopagic',
  'Xylophonic',
  'Youthquake',
  'Zeaxanthin',
  'Zigzaggers',
  'Zigzaggery',
  'Zigzagging',
  'Zincifying',
  'Zombifying',
  'Zoomorphic',
  'Zygobranch',
  'Zygodactyl',
  'Zygomorphy',
  'Zygomycete',
  'Zygophytes',
  'Abbreviating',
  'Abbreviation',
  'Abolitionary',
  'Abolitionism',
  'Abolitionist',
  'Abominations',
  'Abortionists',
  'Abrasiveness',
  'Absentminded1',
  'Absoluteness',
  'Absolutistic',
  'Absorptivity',
  'Absquatulate',
  'Abstemiously',
  'Abstractedly',
  'Abstractions',
  'Abstractness',
  'Abstruseness1',
  'Academically',
  'Academicians',
  'Acantholysis',
  'Accelerating',
  'Acceleration',
  'Accelerative',
  'Accelerators',
  'Acceleratory',
  'Accentuating1',
  'Accentuation',
  'Acciaccatura',
  'Accidentally',
  'Acclamations',
  'Acclimatised',
  'Accommodated',
  'Accommodates',
  'Accommodator',
  'Accompanying2',
  'Accompanyist',
  'Accomplished',
  'Accomplishes',
  'Accordionist',
  'Accouchement',
  'Accouterment',
  'Accoutrement',
  'Accretionary',
  'Accumulating1',
  'Accumulation',
  'Accumulative',
  'Accumulators',
  'Accusatorial',
  'Acetaldehyde',
  'Achievements',
  'Achlamydeous',
  'Achlorhydria',
  'Achlorhydric2',
  'Achromatinic',
  'Acidophilous',
  'Acknowledged',
  'Acknowledges',
  'Acoustically',
  'Acquaintance',
  'Acquiescence',
  'Acquisitions',
  'Acrocyanosis1',
  'Acromyotonia',
  'Actinometric',
  'Actinomycete',
  'Acylglycerol',
  'Adaptability',
  'Adaptational',
  'Additionally',
  'Addlebrained',
  'Adequateness2',
  'Adhesiveness',
  'Adjectivally',
  'Adjudicating',
  'Adjudication',
  'Adjudicative',
  'Adjudicators',
  'Adjudicatory',
  'Administered',
  'Breadwinners',
  'Breakability',
  'Breakfasting',
  'Breakthrough',
  'Breaststroke',
  'Breathalysed',
  'Breathalyser',
  'Breathalyzer',
  'Breathlessly',
  'Breathtaking',
  'Breechloader',
  'Brightnesses',
  'Brilliantine',
  'Brinkmanship',
  'Bachelorette',
  'Bachelorhood',
  'Backbenchers',
  'Backbreaking',
  'Backgrounder',
  'Backlighting',
  'Backpedalled',
  'Backslapping',
  'Backstabbing',
  'Backtracking',
  'Backwardness',
  'Backwoodsman',
  'Backwoodsmen',
  'Bacteriacide',
  'Bacteriaemia',
  'Bactericidal',
  'Bacterioidal',
  'Bacteriology',
  'Bacteriostat',
  'Ballbearings',
  'Balletomania',
  'Ballottement',
  'Banderillero',
  'Bankruptcies',
  'Bantamweight',
  'Barbarically',
  'Barbiturates',
  'Barnstorming',
  'Barometrical',
  'Baroreceptor',
  'Basidiospore',
  'Basketweaver',
  'Battlefields',
  'Battleground',
  'Battlemented',
  'Becomingness',
  'Beethovenian',
  'Befuddlement',
  'Calisthenics',
  'Calligrapher',
  'Calligraphic',
  'Callosectomy',
  'Calorimeters',
  'Calorimetric',
  'Calumniation',
  'Calumniatory',
  'Calumniously',
  'Camouflaging',
  'Campanulated',
  'Canaliculate',
  'Canalisation',
  'Canalization',
  'Cancellation',
  'Candidatures',
  'Candlesticks',
  'Cannibalised',
  'Canonisation',
  'Canonization',
  'Cantankerous',
  'Cantilevered',
  'Cantillation',
  'Canulisation',
  'Canulization',
  'Capabilities',
  'Capercailzie',
  'Capitalising',
  'Capitalistic',
  'Capitalizing',
  'Capitulating',
  'Capitulation',
  'Capriciously',
  'Caravanserai',
  'Carbohydrate',
  'Carbonaceous',
  'Carburettors',
  'Carcinogenic',
  'Cardinalfish',
  'Cardinalship',
  'Cardiography',
  'Cardiologist',
  'Cardiomegaly',
  'Carefreeness',
  'Carelessness',
  'Caricaturist',
  'Carillonneur',
  'Carpetbagger',
  'Carpophagous',
  'Carposporous',
  'Carriageways',
  'Carthaginian',
  'Cartographer',
  'Cartographic',
  'Carunculated',
  'Catachrestic',
  'Catamountain',
  'Cataphoresis',
  'Cataphoretic',
  'Catarrhinian',
  'Catastrophes',
  'Catastrophic',
  'Catchphrases',
  'Catechetical',
  'Categorising',
  'Caterpillars',
  'Cauliflowers',
  'Cautiousness',
  'Cefoperazone',
  'Celebrations',
  'Cementitious',
  'Centenarians',
  'Centennially',
  'Centralisers',
  'Centralising',
  'Centralistic',
  'Centralizing',
  'Centrepieces',
  'Centrifugate',
  'Centrifuging',
  'Cephalometry',
  'Cephalopodan',
  'Ceratosaurus',
  'Decoratively',
  'Decorousness',
  'Decreasingly',
  'Decrementing',
  'Decustomised',
  'Deepfreezing',
  'Deerstalkers',
  'Deerstalking',
  'Defenestrate',
  'Defervescent',
  'Defibrillate',
  'Deficiencies',
  'Definiteness',
  'Definitional',
  'Definitively',
  'Deflagration',
  'Deflationary',
  'Deformations',
  'Degeneracies',
  'Degenerating',
  'Degeneration',
  'Degenerative',
  'Degradations',
  'Dehumanising',
  'Dehumidifier',
  'Deinocheirus',
  'Dejectedness',
  'Deliberately',
  'Deliberating',
  'Deliberation',
  'Deliberative',
  'Delicatessen',
  'Delightfully',
  'Delimitation',
  'Deliquescent',
  'Demarcations',
  'Dementedness',
  'Demilitarise',
  'Demilitarize',
  'Demimondaine',
  'Demineralise',
  'Demineralize',
  'Demodulation',
  'Demographers',
  'Demographics',
  'Demographist',
  'Demoniacally',
  'Demonisation',
  'Demonization',
  'Demonstrable',
  'Demonstrably',
  'Demonstrated',
  'Demonstrates',
  'Demonstrator',
  'Demoralising',
  'Demoralizing',
  'Demystifying',
  'Denaturalise',
  'Denaturalize',
  'Denigrations',
  'Denomination',
  'Denominators',
  'Denotational',
  'Denouncement',
  'Densitometer',
  'Densitometry',
  'Denunciation',
  'Denunciative',
  'Denunciatory',
  'Departmental',
  'Dependencies',
  'Depopulation',
  'Deportations',
  'Depositional',
  'Depositories',
  'Electroplate',
  'Electroscope',
  'Electroshock',
  'Electrosleep',
  'Eleemosynary',
  'Elementarily',
  'Eliminations',
  'Elliptically',
  'Elocutionary',
  'Elocutionist',
  'Emancipating',
  'Emancipation',
  'Emancipative',
  'Emancipatory',
  'Emasculating',
  'Emasculation',
  'Embarrassing',
  'Embellishing',
  'Embezzlement',
  'Embitterment',
  'Emblematical',
  'Embroiderers',
  'Embroideress',
  'Embroideries',
  'Embroidering',
  'Embryologist',
  'Emissivities',
  'Emotionalism',
  'Emotionality',
  'Empathetical',
  'Emphatically',
  'Emplacements',
  'Enamoredness',
  'Enantiomorph',
  'Encapsulated',
  'Encapsulates',
  'Encephalitis',
  'Enchantingly',
  'Enchantments',
  'Encirclement',
  'Encompassing',
  'Encountering',
  'Encroachment',
  'Encrustation',
  'Encumbrances',
  'Encyclopedia',
  'Encyclopedic',
  'Endangerment',
  'Endarteritis',
  'Endeavouring',
  'Endocarditis',
  'Endogenously',
  'Endometritis',
  'Endomorphism',
  'Endonuclease',
  'Endoparasite',
  'Endorsements',
  'Endoskeleton',
  'Enduringness',
  'Enfeeblement',
  'Enforcements',
  'Enfranchised',
  'Enfranchiser',
  'Enhancements',
  'Enjoyability',
  'Enlargements',
  'Enlightening',
  'Enormousness',
  'Entanglement',
  'Enterobiasis',
  'Enteroceptor',
  'Enterokinase',
  'Enteroptosis',
  'Enterprising',
  'Entertainers',
  'Entertaining',
  'Enthrallment',
  'Enthronement',
  'Enthusiastic',
  'Entitlements',
  'Entomologist',
  'Entomophobia',
  'Entoparasite',
  'Flatteringly',
  'Flawlessness',
  'Fleetingness',
  'Flexibleness',
  'Flocculation',
  'Floodlighted',
  'Floriculture',
  'Fluctuations',
  'Fluorapatite',
  'Fluoresceine',
  'Fluorescence',
  'Fluorescents',
  'Fluoridation',
  'Fluoroboride',
  'Fluorocarbon',
  'Fluorochrome',
  'Fluorouracil',
  'Fluosilicate',
  'Fluphenazine',
  'Flurbiprofen',
  'Focalisation',
  'Focalization',
  'Foetoprotein',
  'Folliculitis',
  'Forbiddingly',
  'Forcefeeding',
  'Forcefulness',
  'Foregathered',
  'Foregrounded',
  'Forensically',
  'Foreordained',
  'Foreshadowed',
  'Foresightful',
  'Forestalling',
  'Forgetmenots',
  'Formaldehyde',
  'Formlessness',
  'Galactosemia',
  'Gallinaceous',
  'Gallivanting',
  'Galvanometer',
  'Gamesmanship',
  'Gamopetalous',
  'Garmentmaker',
  'Gasification',
  'Gastrogavage',
  'Gastrolobium',
  'Gastrulation',
  'Gatecrashers',
  'Gatecrashing',
  'Gauguinesque',
  'Genealogical',
  'Generalising',
  'Generalities',
  'Generational',
  'Generosities',
  'Generousness',
  'Genuflection',
  'Geochemistry',
  'Geographical',
  'Geologically',
  'Geomagnetism',
  'Geometrician',
  'Geophysicist',
  'Geopolitical',
  'Geostrategic',
  'Geothermally',
  'Geriatrician',
  'Gerontocracy',
  'Gesticulated',
  'Getrichquick',
  'Giantkillers',
  'Gibraltarian',
  'Gigantically',
  'Glaciologist',
  'Gladiatorial',
  'Heliogravure',
  'Heliotherapy',
  'Heliotropism',
  'Helmetflower',
  'Helplessness',
  'Hematochezia',
  'Hematochrome',
  'Hematocolpos',
  'Hematohiston',
  'Hematologist',
  'Hemiepiphyte',
  'Hemimetaboly',
  'Hemimorphite',
  'Hemiparasite',
  'Hemodialysis',
  'Hemodialyzer',
  'Hemodynamics',
  'Hemstitching',
  'Henceforward',
  'Hepadnavirus',
  'Hepatoflavin',
  'Hepatomegaly',
  'Hereditament',
  'Hereinbefore',
  'Heritability',
  'Hermeneutics',
  'Hermetically',
  'Hesitatingly',
  'Heterocercal',
  'Heterocyclic',
  'Heterodactyl',
  'Heteroecious',
  'Heterogenous',
  'Heterologous',
  'Heteroploidy',
  'Heterosexism',
  'Heterosexist',
  'Heterosexual',
  'Heterozygote',
  'Heterozygous',
  'Heydaymayday',
  'Hierarchical',
  'Hieroglyphic',
  'Higginbotham',
  'Interceptors',
  'Intercession',
  'Interchanged',
  'Interchanges',
  'Interconnect',
  'Intercountry',
  'Intercrossed',
  'Interdiction',
  'Interestedly',
  'Interference',
  'Interglacial',
  'Interjecting',
  'Interjection',
  'Interleaving',
  'Interlingual',
  'Interlinking',
  'Interlobular',
  'Interlocking',
  'Interlocutor',
  'Intermediary',
  'Intermediate',
  'Interminable',
  'Interminably',
  'Intermingled',
  'Intermission',
  'Intermittent',
  'Intermixture',
  'Internalised',
  'Internalises',
  'Internuclear',
  'Interoceptor',
  'Interpellate',
  'Interpolated',
  'Interpolates',
  'Interpreters',
  'Interpreting',
  'Interpretive',
  'Interrelated',
  'Interrogated',
  'Interrogates',
  'Interrogator',
  'Interrupting',
  'Interruption',
  'Intersectant',
  'Intersecting',
  'Intersection',
  'Journalistic',
  'Jumpstarting',
  'Jurisdiction',
  'Juvenescence',
  'Kainogenesis',
  'Kakistocracy',
  'Kaleidoscope',
  'Karyokinesis',
  'Karyokinetic',
  'Katamorphism',
  'Katharometer',
  'Katzenjammer',
  'Keratectasia',
  'Keratodermia',
  'Keratohyalin',
  'Keratoiritis',
  'Keratoplasty',
  'Ketoacidosis',
  'Ketoaciduria',
  'Kickstarting',
  'Kidneyshaped',
  'Kinaesthesia',
  'Kinaesthesis',
  'Kinaesthetic',
  'Kindergarten',
  'Kinesthetics',
  'Kiplingesque',
  'Kleptomaniac',
  'Knightliness',
  'Knucklebones',
  'Labanotation',
  'Laboratories',
  'Laboursaving',
  'Labyrinthian',
  'Labyrinthine',
  'Lachrymation',
  'Lachrymatory',
  'Ladylikeness',
  'Laissezfaire',
  'Lamentations',
  'Lamplighters',
  'Landholdings',
  'Landlubberly',
  'Languorously',
  'Lansoprazole',
  'Laryngectomy',
  'Laryngoscope',
  'Laryngospasm',
  'Lasciviously',
  'Laudableness',
  'Launderettes',
  'Laundrywoma',
  'Mackintoshes',
  'Macrobiotics',
  'Macrocephaly',
  'Macrocytosis',
  'Macroglossia',
  'Mademoiselle',
  'Magistrature',
  'Magnetically',
  'Magnetograph',
  'Magnetometer',
  'Magnificence',
  'Magniloquent',
  'Magnoliopsid',
  'Maidenliness',
  'Maidservants',
  'Mainstreamed',
  'Maintainable',
  'Majestically',
  'Malacologist',
  'Maladjustive',
  'Malefactions',
  'Malevolently',
  'Malformation',
  'Malfunctions',
  'Malignancies',
  'Malleability',
  'Malnourished',
  'Malnutrition',
  'Malocclusion',
  'Malpractices',
  'Maltreatment',
  'Malversation',
  'Manageresses',
  'Managerially',
  'Maneuverable',
  'Manipulating',
  'Manipulation',
  'Manipulative',
  'Manipulators',
  'Mannerliness',
  'Manoeuvrable',
  'Manoeuvrings',
  'Manslaughter',
  'Manspreading',
  'Mantelpieces',
  'Manufactured',
  'Manufacturer',
  'Manufactures',
  'Marginalised',
  'Marginalises',
  'Marketplaces',
  'Marksmanship',
  'Nonheritable',
  'Nonimitative',
  'Nonindulgent',
  'Nonlexically',
  'Nonmandatory',
  'Nonmedicinal',
  'Nonmigratory',
  'Nonmonotonic',
  'Nonnormative',
  'Nonobjective',
  'Nonobservant',
  'Nonparasitic',
  'Nonpasserine',
  'Nonpoisonous',
  'Nonpolitical',
  'Nonrenewable',
  'Nonresilient',
  'Nonresistant',
  'Nonsectarian',
  'Nonsegmental',
  'Nonsensitive',
  'Nonsovereign',
  'Nonspherical',
  'Nonsteroidal',
  'Nonstrategic',
  'Nonsymbiotic',
  'Nonsynthetic',
  'Nontechnical',
  'Nontricyclic',
  'Nonturbulent',
  'Nonunionised',
  'Nonunionized',
  'Nonviolently',
  'Nonvoluntary',
  'Noradrenalin',
  'Oscilloscope',
  'Osmoreceptor',
  'Ossification',
  'Ostentatious',
  'Osteomalacia',
  'Osteopathist',
  'Osteoporosis',
  'Osteosarcoma',
  'Osteostracan',
  'Otherworldly',
  'Otosclerosis',
  'Outbuildings',
  'Outlandishly',
  'Outmanoeuvre',
  'Outnumbering',
  'Outperformed',
  'Outplacement',
  'Outrageously',
  'Outstretched',
  'Outstripping',
  'Overabundant',
  'Overachiever',
  'Overactivity',
  'Overburdened',
  'Overcapacity',
  'Overcautious',
  'Overcharging',
  'Overcritical',
  'Overcrossing',
  'Overcrowding',
  'Overdelicate',
  'Overdramatic',
  'Overemphasis',
  'Overestimate',
  'Overexertion',
  'Overexposure',
  'Prospicience',
  'Prostituting',
  'Prostitution',
  'Protactinium',
  'Protagonists',
  'Protectively',
  'Protectorate',
  'Protestation',
  'Prothalamion',
  'Prothalamium',
  'Protohistory',
  'Protoplasmic',
  'Prototherian',
  'Prototypical',
  'Protozoology',
  'Protractedly',
  'Protractible',
  'Protuberance',
  'Proverbially',
  'Providential',
  'Provincially',
  'Provisionary',
  'Provisioning',
  'Provocations',
  'Psephologist',
  'Pseudocyesis',
  'Pseudonymous',
  'Pseudophloem',
  'Pseudopodium',
  'Psittacosaur',
  'Psychiatrist',
  'Psychoactive',
  'Psychobabble',
  'Psychologies',
  'Psychologist',
  'Psychometric',
  'Psychonomics',
  'Psychopathic',
  'Psychosexual',
  'Psychosocial',
  'Psychotropic',
  'Psychrometer',
  'Pteridophyte',
  'Publications',
  'Pugnaciously',
  'Pumpernickel',
  'Punctuations',
  'Punctureless',
  'Purification',
  'Purposefully',
  'Pussyfooting',
  'Putrefacient',
  'Putrefaction',
  'Putrefactive',
  'Pyridoxamine',
  'Pyrochemical',
  'Pyroelectric',
  'Pyroligneous',
  'Pyromorphite',
  'Pyrophyllite',
  'Quantization',
  'Quarterfinal',
  'Quarterlight',
  'Quarterstaff',
  'Quattrocento',
  'Questionable',
  'Questionably',
  'Questionings',
  'Quinquennial',
  'Quinquennium',
  'Quintessence',
  'Quixotically',
  'Rachischisis',
  'Racketeering',
  'Radiobiology',
  'Radiochemist',
  'Radiographer',
  'Radiographic',
  'Radioisotope',
  'Radiological',
  'Radiologists',
  'Radionuclide',
  'Radiotherapy',
  'Radiothorium',
  'Ragstoriches',
  'Rambunctious',
  'Ramification',
  'Rarefactions',
  'Ratification',
  'Ratiocinator',
  'Rationalised',
  'Rationalists',
  'Rationalness',
  'Rattlesnakes',
  'Ravenousness',
  'Reabsorption',
  'Reactivating',
  'Reactivation',
  'Reactivities',
  'Readjustment',
  'Realignments',
  'Realisations',
  'Reallocating',
  'Reallocation',
  'Reappearance',
  'Reappraising',
  'Reassembling',
  'Snobbishness',
  'Snowboarding',
  'Sociableness',
  'Sociobiology',
  'Sociological',
  'Sociologists',
  'Solarisation',
  'Solarization',
  'Solenogaster',
  'Solicitation',
  'Solicitously',
  'Solitariness',
  'Somaesthesia',
  'Somaesthesis',
  'Somatotropin',
  'Somersaulted',
  'Somnambulate',
  'Somnambulism',
  'Somnambulist',
  'Somniloquism',
  'Somniloquist',
  'Sonorousness',
  'Sophisticate',
  'Soporiferous',
  'Sorbefacient',
  'Soundproofed',
  'Southeastern',
  'Southernmost',
  'Southernness',
  'Southernwood',
  'Southwestern',
  'Spaciousness',
  'Sparkleberry',
  'Speakerphone',
  'Spearheading',
  'Specialising',
  'Specialistic',
  'Specialities',
  'Specifically',
  'Specificness',
  'Speciousness',
  'Spectaculars',
  'Spectrograph',
  'Spectrometer',
  'Spectrometry',
  'Spectroscope',
  'Spectroscopy',
  'Speculations',
  'Speechifying',
  'Speechlessly',
  'Speechmaking',
  'Speechwriter',
  'Speedometers',
  'Speleologist',
  'Spellbinding',
  'Spermatocele',
  'Spermatocide',
  'Spermatocyte',
  'Spermatozoan',
  'Spermatozoid',
  'Spermatozoon',
  'Spiderflower',
  'Spiegeleisen',
  'Spindleberry',
  'Spinnability',
  'Spinnbarkeit',
  'Spinsterhood',
  'Terribleness',
  'Terrifically',
  'Terrifyingly',
  'Tertigravida',
  'Tessellation',
  'Testamentary',
  'Testimonials',
  'Testosterone',
  'Tetartanopia',
  'Tetracycline',
  'Tetrahedrons',
  'Tetraskelion',
  'Tetrodotoxin',
  'Thalassaemia',
  'Thallophytic',
  'Thankfulness',
  'Thanksgiving',
  'Theatrically',
  'Thematically',
  'Theophylline',
  'Theoretician',
  'Theorisation',
  'Theorization',
  'Theosophical',
  'Therapeutics',
  'Thereinafter',
  'Thermalgesia',
  'Thermocouple',
  'Thermography',
  'Thermolabile',
  'Thermometers',
  'Thermometric',
  'Thermosphere',
  'Thermostatic',
  'Thickskinned',
  'puttanella',
  'Unbecomingly',
  'Unbelievable',
  'Unbelievably',
  'Unblinkingly',
  'Unblushingly',
  'Unbridgeable',
  'Uncalibrated',
  'Uncarbonated',
  'Uncatalogued',
  'Uncelebrated',
  'Unceremonial',
  'Unchallenged',
  'Unchangeable',
  'Unchangeably',
  'Unchaperoned',
  'Uncharitable',
  'Uncharitably',
  'Unchivalrous',
  'Unchristened',
  'Unchristlike',
  'Unchronicled',
  'Unclassified',
  'Uncollimated',
  'Uncommercial',
  'Uncommonness',
  'Uncomparable',
  'Uncomparably',
  'Uncompilable',
  'Uncompounded',
  'Uncompressed',
  'Unconformist',
  'Unconsidered',
  'Unconsolable',
  'Unconstraint',
  'Uncontrolled',
  'Unconvincing',
  'Uncorrelated',
  'Uncritically',
  'Unctuousness',
  'Vanquishable',
  'Vaporisation',
  'Vaporization',
  'Vaporousness',
  'Vapourisable',
  'Variableness',
  'Varicoloured',
  'Vasodilation',
  'Vasodilative',
  'Vaticination',
  'Vaudevillian',
  'Vegetational',
  'Velociraptor',
  'Venerability',
  'Vengefulness',
  'Venipuncture',
  'Verification',
  'Verificatory',
  'Vermiculated',
  'Verticalness',
  'Verticillate',
  'Vesicopapule',
  'Vesiculation',
  'Veterinarian',
  'Vibraphonist',
  'Vicissitudes',
  'Victoriously',
  'Videographer',
  'Vilification',
  'Vindictively',
  'Vinegariness',
  'Vinification',
  'Virilisation',
  'Virilization',
  'Volunteering',
  'Voluptuously',
  'Waggonwright',
  'Wainscotting',
  'Walkietalkie',
  'Walkingstick',
  'Wallpapering',
  'Warehouseman',
  'Warehousemen',
  'Warmongering',
  'Wastefulness',
  'Watchfulness',
  'Watercolours',
  'Watercourses',
  'Waterproofed',
  'Watersoluble',
  'Weatherboard',
  'Weatherbound',
  'Weathercocks',
  'Weatherglass',
  'Weatherproof',
  'Weatherstrip',
  'Weightlessly',
  'Weightlifter',
  'Weisenheimer',
  'Zoomastigote',
  'Zygomorphous',
];

// //ITALIANO
// easy = [
//   'prova',
//   'pippo',
//   'pluto',
//   'ciao',
//   'gatto',
//   'cane',
//   'lello',
//   'lallo',
//   'abato',
//   'abbai',
//   'abbia',
//   'bacca',
//   'bacco',
//   'bachi',
//   'bacia',
//   'calza',
//   'calze',
//   'calzi',
//   'calzo',
//   'dande',
//   'dando',
//   'dandy',
//   'danna',
//   'edera',
//   'edere',
//   'edile',
//   'edili',
//   'edipo',
//   'fallo',
//   'falsa',
//   'gabba',
//   'gabbi',
//   'gabbo',
//   'gemei',
//   'gemma',
//   'gemme',
//   'lacca',
//   'lacci',
//   'lacco',
//   'mamba',
//   'mambo',
//   'mamma',
//   'mamme',
//   'nesto',
//   'netta',
//   'nette',
//   'netti',
//   'pacca',
//   'pacco',
//   'padre',
//   'padri',
//   'paese',
//   'sabba',
//   'sabea',
//   'sabee',
//   'sabei',
//   'zoppa',
//   'zoppe',
//   'zoppi',
//   'zoppo',
//   'zorro',
// ];
// medium = [
//   'aborro',
//   'bacare',
//   'cubato',
//   'debora',
//   'fibbia',
//   'labbra',
//   'scriba',
//   'sbobba',
//   'sbirro',
//   'tabico',
//   'abanese',
//   'abarica',
//   'ansando',
//   'anselma',
//   'bandone',
//   'bangkok',
//   'calamio',
//   'calanca',
//   'canguro',
//   'canizie',
//   'dairago',
//   'dalmata',
//   'eforato',
//   'egemone',
//   'guaisca',
//   'guamano',
//   'imbimbo',
//   'imborga',
//   'ipossia',
//   'ipoteca',
//   'jogging',
//   'kampala',
//   'lagnoso',
//   'lagundo',
//   'maizena',
//   'malacca',
//   'malanno',
//   'malaria',
//   'nefrone',
//   'nefrosi',
//   'negando',
//   'negarit',
//   'oliario',
//   'olibano',
//   'olimpia',
//   'olimpio',
//   'palilie',
//   'palizzi',
//   'pallade',
//   'pallaio',
//   'radazza',
//   'radendo',
//   'radenza',
//   'rameico',
//   'ramengo',
//   'rameoso',
//   'rametto',
//   'samurai',
//   'sanando',
//   'sancire',
//   'sanctus',
//   'sandalo',
//   'tallone',
//   'talpone',
//   'tamburo',
//   'tampoco',
//   'tampone',
//   'tanagra',
//   'tananai',
//   'uremica',
//   'uremico',
//   'uretere',
//   'urgente',
//   'urgenza',
//   'vacando',
//   'vacanza',
//   'vacatio',
//   'vaccaio',
//   'vaccaro',
//   'vaccata',
//   'vaccine',
//   'vacinai',
//   'zaffare',
//   'zaffato',
//   'zaffiro',
//   'xantoma',
//   'xerobio',
//   'xilosio',
//   'zannata',
//   'zannuto',
//   'zanzara',
//   'zappare',
//   'zappato',
// ];
// hard = [
//   'abduttore',
//   'abduzione',
//   'abelmosco',
//   'aberrando',
//   'belzarini',
//   'bendaggio',
//   'bendatura',
//   'capibarca',
//   'capicarro',
//   'capicollo',
//   'dedicando',
//   'dedizione',
//   'deducendo',
//   'edochiana',
//   'edochiano',
//   'educabile',
//   'educativa',
//   'faustismo',
//   'favagello',
//   'favaretto',
//   'favellare',
//   'gelazione',
//   'gelicidio',
//   'gelignite',
//   'igienista',
//   'ignifughe',
//   'ignizione',
//   'lanzafama',
//   'laocoonte',
//   'laodiceno',
//   'lapidando',
//   'lapidario',
//   'kayakista',
//   'kellerina',
//   'Kurdistan',
//   'manlevato',
//   'manomesso',
//   'manometro',
//   'manomorta',
//   'neogotico',
//   'neoguelfo',
//   'neolatino',
//   'oceaniana',
//   'oceaniano',
//   'oceanside',
//   'parafuoco',
//   'paragocce',
//   'paralalia',
//   'quantomai',
//   'quaresima',
//   'quarteria',
//   'quartetto',
//   'referendi',
//   'referendo',
//   'referente',
//   'saponiero',
//   'saprofago',
//   'saprofilo',
//   'tahitiano',
//   'taiwanese',
//   'talabacco',
//   'ubriacone',
//   'uccellaia',
//   'uccellaio',
//   'uccellare',
//   'venagione',
//   'venatorio',
//   'venceslao',
//   'vendemmia',
//   'wattmetro',
//   'wehrmacht',
//   'wisconsin',
//   'wrestling',
//   'xantopsia',
//   'xenofilia',
//   'xenofobia',
//   'xenogamia',
//   'yachtsman',
//   'zafferano',
//   'zampaccia',
//   'zampirone',
//   'abbandonare',
//   'abbandonata',
//   'balbettasti',
//   'balbetterai',
//   'balbetterei',
//   'calamaretto',
//   'calambucchi',
//   'calamitammo',
//   'debordavate',
//   'deborderemo',
//   'eccitazioni',
//   'ecciteranno',
//   'fagocitanti',
//   'fagocitaria',
//   'galoppatore',
//   'icnografica',
//   'icnografici',
//   'jazzistiche',
//   'judoistiche',
//   'ladroncello',
//   'ladronesche',
//   'macerassimo',
//   'maceratrice',
//   'nasolabiali',
//   'nastratrice',
//   'obbediranno',
//   'obbedirebbe',
//   'pacatamente',
//   'pacchianata',
//   'quadernacci',
//   'quadernaria',
//   'raccattaste',
//   'raccattasti',
//   'saccentello',
//   'saccenteria',
//   'tagliassero',
//   'tagliassimo',
//   'uccidendovi',
//   'uccideranno',
//   'valicassero',
//   'valicassimo',
//   'workstation',
//   'xantogenata',
//   'zampillando',
//   'zappettante',
// ];
